# Changes here will be overwritten by Copier
_commit: v7.3.0-24-g169e035
_src_path: gh:eccenca/cmem-plugin-template
author_mail: thomas.wilmering@eccenca.com
author_name: Thomas Wilmering
github_page: https://github.com/eccenca/cmem-plugin-parameters/
project_description: Set or overwrite parameters of a task.
project_slug: parameters
project_type: plugin
pypi: true

