# Changes here will be overwritten by Copier
_commit: v4.1.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-parameters
project_description: eccenca Corporate Memory Workflow plugin for parameter input
project_slug: parameters
pypi: true

