# Changes here will be overwritten by Copier
_commit: v5.3.2-4-gfcbfe6f
_src_path: gh:eccenca/cmem-plugin-template
author_mail: thomas.wilmering@eccenca.com
author_name: Thomas Wilmering
github_page: https://github.com/eccenca/cmem-plugin-parameters/
project_description: Set or overwrite parameters of a task.
project_slug: parameters
pypi: true

