# Changes here will be overwritten by Copier
_commit: v3.4.1
_src_path: gh:eccenca/cmem-plugin-template
author_mail: thomas.wilmering@eccenca.com
author_name: Thomas Wilmering
project_description: eccenca Corporate Memory Workflow plugin for parameter input
project_slug: parameters

